### ISSUE TITLE
Module ID

### ISSUE THREAD

**Issue by Atrate** [Magisk-Modules-Alt-Repo/AFWall-Boot-AntiLeak#2] opened 2021-12-26 00:56 UTC
Hey there @gjf ,

I noticed an oversight. In the Submission Guidelines at https://github.com/Magisk-Modules-Alt-Repo/submission, it is stated that:

> Module ID must match repo name (otherwise Magisk Manager fails to download it).

I have noticed that this is not the case for your module. Could you please fix that?

**Comment by gjf** [comment] 2021-12-26 13:26
Fixed. Thank you.

**Comment by gjf** [comment] 2021-12-26 14:12
@Atrate The issue is more complex than I thought.
I have changed the module ID however it cannot be found in Fox's Mmm.
At the same time some modules with "id - repo name" mismatch can be easily found: https://github.com/Magisk-Modules-Alt-Repo/Zeetaa-Tweaks and https://github.com/Magisk-Modules-Alt-Repo/magisk-module-koruri-font for instance.
I have no idea what is wrong and it seems a repository error, not mine.

**Comment by Atrate** [comment] 2021-12-26 14:55
@tytydraco Ideas?

**Comment by tytydraco** [comment] 2021-12-26 18:02
Well it looks like your module is fine:
https://github.com/Magisk-Modules-Alt-Repo/json/blob/main/modules.json#L5

It's found in the JSON, so your repo is live. Have you tried clearing the module cache in MM yet?

**Comment by gjf** [comment] 2021-12-26 19:22
> Well it looks like your module is fine:
> https://github.com/Magisk-Modules-Alt-Repo/json/blob/main/modules.json#L5
> 
> It's found in the JSON, so your repo is live. Have you tried clearing the module cache in MM yet? 

I've cleaned a cache and module appears. Weird the app does not do it by itself when updating info.
Now we have a new surprise:
 ![Screenshot_20211226-222023.jpg](https://user-images.githubusercontent.com/322186/147418019-2c41921c-94a2-4ccf-bb44-c4c45509627b.jpg)

Should I create zip by myself and place it somewhere? In original rep I shouldn't.

**Comment by tytydraco** [comment] 2021-12-26 19:25
Very very strange here. Try zipping it anyway and checking. That will check if it's a repo issue or MM issue.

**Comment by gjf** [comment] 2021-12-26 20:14
> Very very strange here. Try zipping it anyway and checking. That will check if it's a repo issue or MM issue.

All right let's play.
I have archived a repo content into zip. Here we go:
[AFWall-Boot-AntiLeak-main.zip](https://github.com/Magisk-Modules-Alt-Repo/AFWall-Boot-AntiLeak/files/7777510/AFWall-Boot-AntiLeak-main.zip)

Now I open MM and try to download and install a module from repo. The same error as above.

Then I try to install an attached zip. No problem:

![Screenshot_20211226-231355.jpg](https://user-images.githubusercontent.com/322186/147419052-2338a143-2b25-401f-9632-9eb9301e440e.jpg)

**Comment by tytydraco** [comment] 2021-12-26 21:03
So that means magisk manager isn't downloading the zip properly. Let's try and see if maybe @Atrate can download it from MM. Is there any logs in the app that show the actual error?

**Comment by gjf** [comment] 2021-12-26 22:59
> So that means magisk manager isn't downloading the zip properly. Let's try and see if maybe @Atrate can download it from MM. Is there any logs in the app that show the actual error?

Frankly speaking I am new with MM. Actually I was even surprised zips are not downloaded at Download folder like original Magisk app did.

So if you tell me how to collect any specific logs - I will do.

**Comment by Fox2Code** [comment] 2021-12-28 16:15
I will just wait for @tytydraco to close this issue directly, and wait for next json update before saying anything.

**Comment by tytydraco** [comment] 2021-12-28 21:17
If the issue is fixed we can close. @gjf can you confirm? @Fox2Code made a commit that should fix the issue

**Comment by gjf** [comment] 2021-12-28 21:26
> If the issue is fixed we can close. @gjf can you confirm? @Fox2Code made a commit that should fix the issue 

0.2.5 is still affected. So it looks like a commit was not integrated into the release yet.

**Comment by Fox2Code** [comment] 2021-12-28 21:27
Should be fixed, it was a Magisk-Modules-Alt-Repo issue, I worked directly with @tytydraco to fix the issue.

**Closed as completed by Fox2Code** 2021-12-28 21:27 UTC
Labels: bug

**Comment by Fox2Code** [comment] 2021-12-28 21:31
The issue is that the json generator was always using the "master" branch, it use the default repo branch now, so it's fixed now!
Fixed there: <https://github.com/Magisk-Modules-Alt-Repo/json/commit/b23cef53b6c494aca49f93ec98184aeb1a0ed61a>
